
services:
  scraper-api:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: gmaps_scraper_api_service # Optional: specify a container name
    ports:
      - "8001-8004:8001" # Map host port 8001 to container port 8001
    restart: unless-stopped # Restart policy
    volumes:
      - .:/app # Mount current directory to /app in container
    working_dir: /app # Set working directory to mounted volume
    # Optional: Add environment variables if needed for configuration
    # environment:
    #   - HEADLESS_MODE=true
    networks:
      - shark
    cpu_shares: 1024 # Add cpu_shares here if not using Swarm mode
#   deploy:
#      replicas: 4
#      resources:
#        limits:
#          cpus: '1'
#          memory: 2G

networks:
  shark:
   external: true